server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}